import { KpiCards } from "@/components/dashboard/kpi-cards";
import { MainChart } from "@/components/dashboard/main-chart";
import { ConversionRateChart } from "@/components/dashboard/conversion-rate-chart";
import { QuarterChart } from "@/components/dashboard/quarter-chart";
import { DayOfWeekChart } from "@/components/dashboard/day-of-week-chart";
import { SeasonalityChart } from "@/components/dashboard/seasonality-chart";
import { MonthlyTable } from "@/components/dashboard/monthly-table";
import { AnalysisReport } from "@/components/dashboard/analysis-report";

export default function Home() {
  return (
    <div className="mx-auto max-w-6xl space-y-6 p-6">
      <header>
        <h1 className="text-2xl font-bold">カラーミーショップ 申込数・契約数 予測分析</h1>
        <p className="text-muted-foreground mt-1 text-sm">
          2025年1月〜2026年12月（2026年3月以降は予測値） | 作成日: 2026年2月18日
        </p>
      </header>

      <KpiCards />

      <MainChart />

      <div className="grid gap-6 lg:grid-cols-2">
        <ConversionRateChart />
        <QuarterChart />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <DayOfWeekChart />
        <SeasonalityChart />
      </div>

      <MonthlyTable />

      <AnalysisReport />

      <footer className="text-muted-foreground py-4 text-center text-xs">
        Generated by Claude | Data source: カラーミーショップ 申込数と契約数.xlsx
      </footer>
    </div>
  );
}
